#include <fstream>
#include <iostream>

int main(int argc, char *argv[]) {

  std::fstream coe_file(argv[1], std::ios::trunc | std::ios::out);

  if (coe_file.is_open()) {
    coe_file << "; This is an autogenerated file\n";
    coe_file << "memory_initialization_radix=16;\n";
    coe_file << "memory_initialization_vector=\n";

    for (int i = 1; i < 65; i++) {
      float y = i;
      coe_file << std::hex << *((int*)&y) << ( i == 64 ? ";" : ",\n");
    }

  } else {
    std::cout << "File [" << argv[1] << "] did not open!!\n";
    return -1; 
  }

  return 0;
}